### ISSUE TITLE
Update to 1.20.1?

### ISSUE THREAD

**Issue by Wiresgaming** [scriptcoded/scripts-chunk-loaders#10]
Not certain if this is the right spot for it, but any chance we could get an update to 1.20.1?

**Comment by scriptcoded** [comment]
Hey! Yes this is certainly the right spot to ask this!

I've been wanting to be able to support multiple versions of Minecraft and also release automatically when new versions of Fabric are released, but I haven't had the time to do any significant work on that front. If my memory doesn't betray me I'll try and make a few catch-up releases this evening. Maybe to [scriptcoded/scripts-](https://github.com/scriptcoded/scripts-difficulty-balancer) as well :smile: I'll keep this issue open meanwhile.

Thanks for the reminder!

**Comment by youmukonpaku1337** [comment]
oh wow this was recent

**Comment by youmukonpaku1337** [comment]
a 1.20.4 update would be awesome as i have some horribly funny ideas of what to do with this

**Comment by scriptcoded** [comment]
@Wiresgaming 1.20.1 released :tada: https://modrinth.com/mod/scripts-chunk-loaders/version/mc1.20.1-0.2.1

There have been some API changes made in 1.20.2 so I'll have to look in to that another day. 1.20.4 should be coming soon :)

**Comment by youmukonpaku1337** [comment]
hell yeah

**Comment by scriptcoded** [comment]
Hey again @Wiresgaming and @youmukonpaku1337!

1.20.4 is now released! 🎉  You can find it here: https://modrinth.com/mod/scripts-chunk-loaders/version/mc1.20.4-0.2.4

I'm closing this issue. If something is not working as expected, you're missing some functionality or just have suggestions, feel free to open a new issue.
