### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by Craemon** [scriptcoded/scripts-chunk-loaders#20]
Hey, could you update the mod to the new Minecraft versions? Don't mean to bother you, would be really nice though:)

Did a bit of testing by changing the version dependencies and the only thing that seemed broken to me is the "_setChunkLoaderNameFromInventory_"  function.
The minecart is being made a chunkloader when empty but when carrying an item it crashes the server.
That being said I don't know much about modding!

Thank you for this great mod :)

**Comment by Craemon** [comment]
Same goes for Minecraft 1.21 I guess:)

**Comment by Smalldero** [comment]
If you need an update right away and don't want to wait for the official release, you can take the updated version [from my fork](https://github.com/Smalldero/scripts-chunk-loaders/releases/tag/1.21) - there were only two little fixes needed so everything should work like before but I guarantee nothing :D

**Comment by scriptcoded** [comment]
Hey! I totally missed this, sorry!

@Smalldero would you be willing to open a PR from your fork to this repo so we can get this out to everyone? 😊

**Comment by Smalldero** [comment]
@scriptcoded Sure, I created a PR!

**Comment by scriptcoded** [comment]
Thanks to @Smalldero [1.21 is now released on Modrinth](https://modrinth.com/mod/scripts-chunk-loaders/version/mc1.21-0.3.1)! 🎉
