### ISSUE TITLE
Not picking up items after portal travel

### ISSUE THREAD

**Issue by MrPrisma** [scriptcoded/scripts-chunk-loaders#21]
Hello,
I have an issue with the Minecart chunk loader. It can't pick up items from an automated loading system after traveling through a portal. I'm using the loading system from this video: https://www.youtube.com/watch?v=t-cWqvP8rw0

When I create the Minecart Chunkloader, its name appears above the cart. It travels normally to the loading system, waits until it's full, and then goes to the portal. It stops at the queue, goes through the portal, and encounters a cobweb on the other side due to the 30-second entity portal delay. When the minecart returns, the name above it disappears (though the green glitter effect remains), and it no longer stops at the auto loader.

Is this a known error, or am I doing something wrong?

Thanks for your help.

**Comment by scriptcoded** [comment]
Hey! Sorry, I've been bad at checking my GitHub notifications lately.

That sounds very interesting... I'll see if I can check on this in the coming days - no promises though!

**Comment by scriptcoded** [comment]
Hi again @MrPrisma!

We just updated to 1.21 and I can't seem to reproduce this in the latest release. Could you please check and verify if this is still an issue? Thanks!

Latest release: https://modrinth.com/mod/scripts-chunk-loaders/version/mc1.21-0.3.1

**Comment by MrPrisma** [comment]
Hello @scriptcoded ,
thank you for your response.

While building a test world with the update, I noticed that everything works perfectly! 
So ill say thanks to you and @Smalldero for the fast update. :)

If I notice anything else, Ill let you know.
o7

**Comment by scriptcoded** [comment]
@MrPrisma Great! And thanks for double checking 😊
